### ISSUE TITLE
Typing on `useContentfulEntry`

### ISSUE THREAD

**Issue by logan-anderson** [tinalabs/tinacms-contentful#13]
# Problem
Example
```ts
const [entry] = useContentfulEntry(
    process.env.CONTENTFUL_SPACE_ID || "",
    DATA_ID,
    {}
  );

console.log(entry?.fields.body)
```
we get this error "Property 'body' does not exist on type 'Entry<any>'".

Typing this should be an opt-in feature, not a forced feature (this way it works for javascript)

# Expected Result
the above code sample should not have type errors the default behavior should be
```ts
const [entry] = useContentfulEntry<any>(
    process.env.CONTENTFUL_SPACE_ID || "",
    DATA_ID,
    {}
  );
```

**Comment by chrisdmacrae** [comment]
@logan-anderson is this behaviour resolved now?
