### ISSUE TITLE
Package will not build

### ISSUE THREAD

**Issue by logan-anderson** [tinalabs/tinacms-contentful#24]
When trying to build the package with `npm run build` or `yarn build` I get this error.

```
react-tinacms-contentful/src/hooks/useContentfulEntry.ts(5,34): semantic error TS2307: Cannot find module '../../dist' or its corresponding type declarations.
```

I run `npm install` before building (also tried with yarn)

**Comment by logan-anderson** [comment]
it seems that changing `import { ContentfulClient } from '../../dist';` to `import { ContentfulClient } from 'tinacms-contentful';`
fixes it. is this the correct fix @chrisdmacrae

**Comment by logan-anderson** [comment]
#25 should fix this issue

**Comment by chrisdmacrae** [comment]
@logan-anderson good catch, looks like my IDE made a mistake on the last minor patch
