### ISSUE TITLE
Question on Docs

### ISSUE THREAD

**Issue by praneybehl** [tinalabs/tinacms-contentful#37]
Hi fellows,
Tina + Contenful is a great combination. Thanks for building the packages. 
I am looking to integrate Tina + Contentful myself and see that the docs are half baked, any chance on getting a quick working example? 
Problem is I am new to both Tina and Contentful myself, but would like to help out where I can.

Please let me know if there is anything I could do to help?

Cheers

**Comment by chrisdmacrae** [comment]
@praneybehl the docs are landing shortly. #39
